export const DefaultState = {
  companyImage: process.env.PUBLIC_URL + '/placeholder-image.png',
  companyName: 'Company Name',
  mainImage: process.env.PUBLIC_URL + '/placeholder-image.png',
  mainImageTagline: 'Your amazing call-to-action here!',
  mainImageButtonCopy: 'Free Download',
  content: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
  cta: 'Call Now',
  footerAddress: 'Company Address',
  headerBGColor: "#ffffff",
  footerBGColor: "#ffffff",
  mainImageTaglineBG: "#ffffff",
  mainImageButtonLink: "",
  ctaButtonLink: "",
  headerLink: "",
}
